### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by KENPOKASMMA1982** [milkotodorov/tt-tool#1]
HELLO MAN...CONGRATULATIONS FOR YOUR AMAZING PROJECT!!!BUT COULD YOU PLEASE TELL ME STEP BY STEP WHAT I HAVE TO DO FOR USE YOUR AMAZING PROJECT?I AM NEW ON THIS AND I DONT KNOW!!!

**Comment by milkotodorov** [comment]
Hello, read the [README](https://github.com/milkotodorov/tt-tool/blob/main/README.md). And just download the binary from the [release section](https://github.com/milkotodorov/tt-tool/releases). If you have concrete question - feel free to ask.
